version: '3.7'

services:
  db:
    image: postgres
    container_name: postgres-meuatelie
    environment:
      POSTGRES_DB: 'meu_atelie'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5432:5432'
    volumes:
      - meuatelie_data:/var/lib/postgres
    networks:
      - meuatelie_network

  backend:
    build: ./backend/.
    container_name: backend-meuatelie
    environment:
      DB_HOST: 'db'
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - meuatelie_network

  frontend:
    build: ./frontend/.
    container_name: frontend-meuatelie
    environment:
      BACKEND_HOST: 'backend'
    ports:
      - '4200:4200'
    networks:
      - meuatelie_network
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'

networks:
  meuatelie_network:
    driver: bridge

volumes:
  meuatelie_data:
